/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package KUIS;

/**
 *
 * @author Rizky
 */
public class KUIS1 extends javax.swing.JFrame {

    /**
     * Creates new form KUIS1
     */
    public KUIS1() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Nama1 = new javax.swing.JTextField();
        Absen1 = new javax.swing.JTextField();
        Matpel1 = new javax.swing.JTextField();
        Nilai1 = new javax.swing.JTextField();
        Proses = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("PENILAIAN SISWA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(136, 11, 107, 14);

        jLabel2.setText("Nama");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(21, 31, 60, 14);

        jLabel3.setText("Absen");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(21, 70, 60, 14);

        jLabel4.setText("Nilai");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(21, 150, 60, 14);

        jLabel5.setText("Matpel");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(21, 111, 60, 14);
        getContentPane().add(Nama1);
        Nama1.setBounds(91, 31, 216, 28);

        Absen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Absen1ActionPerformed(evt);
            }
        });
        getContentPane().add(Absen1);
        Absen1.setBounds(91, 70, 216, 24);
        getContentPane().add(Matpel1);
        Matpel1.setBounds(91, 111, 216, 26);
        getContentPane().add(Nilai1);
        Nilai1.setBounds(91, 144, 216, 27);

        Proses.setText("Proses");
        Proses.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesActionPerformed(evt);
            }
        });
        getContentPane().add(Proses);
        Proses.setBounds(122, 202, 103, 23);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(49, 243, 266, 229);

        setBounds(0, 0, 416, 630);
    }// </editor-fold>//GEN-END:initComponents

    private void Absen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Absen1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Absen1ActionPerformed

    private void ProsesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProsesActionPerformed
        String nama = Nama1.getText();
        String Absen = Absen1.getText();
        String Matpel = Matpel1.getText();

        String ket1 = "Siswa Tidak Lulus";
        String ket2 = "Siswa Lulus";
        String ket3 = "Sempurna";
        String ket4 = "Amazing";

        int nilai = Integer.parseInt(Nilai1.getText());

            if (nilai > 100) {
                TA.setText("Nama Siswa : " + nama + "\n" + "Absen : " + Absen + "\n" + "Matpel : " + Matpel + "\n" + " Nilai  :" + nilai + "\n" + "Keterangan  :" + ket4);
            }
            else if (nilai >75&& nilai==100) {
                TA.setText("Nama Siswa : " + nama + "\n" + "Absen : " + Absen + "\n" + "Matpel : " + Matpel + "\n" + " Nilai  :" + nilai + "\n" + "Keterangan  :" + ket3);
            }
            else if (nilai ==75) {
                TA.setText("Nama Siswa : " + nama + "\n" + "Absen : " + Absen + "\n" + "Matpel : " + Matpel + "\n" + " Nilai  :" + nilai + "\n" + "Keterangan  :" + ket2);
            }else{
                TA.setText("Nama Siswa : " + nama + "\n" + "Absen : " + Absen + "\n" + "Matpel : " + Matpel + "\n" + " Nilai  :" + nilai + "\n" + "Keterangan  :" + ket1);
            }
        

    }//GEN-LAST:event_ProsesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(KUIS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(KUIS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(KUIS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(KUIS1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new KUIS1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Absen1;
    private javax.swing.JTextField Matpel1;
    private javax.swing.JTextField Nama1;
    private javax.swing.JTextField Nilai1;
    private javax.swing.JButton Proses;
    private javax.swing.JTextArea TA;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
